#ifndef SIMPLEWHEEL_GLOBAL_H
#define SIMPLEWHEEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMPLEWHEEL_LIBRARY)
#  define SIMPLEWHEELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMPLEWHEELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLEWHEEL_GLOBAL_H
